spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    \u4E0D\u914D\uFF0C\u9ED8\u8BA4\u4F7F\u7528tomcat\u7684\u6570\u636E\u6E90
    #type: com.alibaba.druid.pool.DruidDataSource

#\u9A7C\u5CF0\u547D\u540D
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台日志配置  打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

#\u4FEE\u6539\u65E5\u5FD7
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
