spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 39.96.18.72
    port: 6379
    password: lxs
  rabbitmq:
    addresses: 39.96.18.72
    port: 5672
    username: guest
    password: guest

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台日志配置  打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

## 设置session 过期时间 单位 S 不能低于 1min
#server:
#  servlet:
#    session:
#      timeout:
server:
  port: 8081


#mqtt config
mqtt:
  username: admin                   # 用户名
  password: public                  # 密码
  url: tcp://123.207.85.44:8090     # 地址
  completionTimeout: 3000           # 超时时间
  producer: # 生产者
    clientId: mqttProducer          # 生产者ID
    defaultTopic: topic             # 默认发布主题
  consumer: # 消费者
    clientId: ${random.value}          # 消费者ID
    defaultTopic: /edgeAdaptor/register,/edgeAdaptor/register/udpate,/device/+/+/status,/device/+/+/+/data/+/up,/device/+/+/guard/up  #默认定义主题

upload:
  path:
    win: D:/upload/
    linux: /data/file/
